// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginInput struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

type NewTodo struct {
	Text    string `json:"text"`
	UserID  string `json:"userId"`
	UserID2 string `json:"userId2"`
}

type RegisterInput struct {
	Email    string  `json:"email"`
	FullName *string `json:"fullName"`
	Password *string `json:"password"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	Email    string `json:"email"`
	FullName string `json:"fullName"`
	ID       string `json:"id"`
}
